### 고객 등록
POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
  "customerName": "홍길동",
  "phoneNumber": "010-1234-5678"
}

### 고객 조회
GET http://localhost:8080/api/v1/customers/cus_mPKEehbj5wakXQU0

